[package]
name = "twitch"
version = "0.1.0"
authors = ["jprochazk <honza.spacir@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
irc-rust = "0.4.0"
pretty_assertions = "1.0.0"
twitch-irc = "5.0.0"

[[bench]]
name = "parse"
harness = false

[profile.release]
lto = "fat"
