[package]
name = "twitch"
version = "0.2.0"
authors = ["jprochazk <honza.spacir@gmail.com>"]
edition = "2021"
license = "MIT"

[features]
simd = []

[dependencies]

[dev-dependencies]
twitch-irc = "5.0.0"
mimalloc = { version = "0.1.37", default-features = false }

criterion = "0.5.1"
pretty_assertions = "1.0.0"

futures-util = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }
tokio-tungstenite = "0.19.0"

[[bench]]
name = "parse"
harness = false

[profile.bench]
lto = "fat"

[profile.release]
lto = "fat"

[profile.release-debug]
inherits = "release"
debug = true
