[package]
name = "twitch"
version = "0.0.1"
authors = ["jprochazk <honza.spacir@gmail.com>"]
edition = "2018"


[dependencies]
thiserror = "1.0.23"
chrono = "0.4.19"
pretty_assertions = "1.0.0"
tokio = { version = "1.4.0", features = ["net", "time"] }
# tokio-util = { version = "0.6.5", features = ["full"] }
tokio-stream = { version = "0.1.5", features = ["io-util"] }
tokio-rustls = "0.23.1"
tokio-tungstenite = { version = "0.16.0", features = ["connect", "rustls-tls-native-roots"]}
rustls-native-certs = "0.6.1"
futures = "0.3.13"
log = "0.4.14"
rand = "0.8.3"
lazy_static = "1.4.0"
unicode-segmentation = "1.7.1"
governor = "0.3.2"
twitch_getters = { path = "./twitch_getters" }
serde = { version = "1", features = ["std", "derive"]}
serde_json = "1"

[dev-dependencies]
anyhow = "1.0.39"
tokio-test = "0.4.0"
alto_logger = "0.3.7"
tokio = { version = "1.4.0", features = ["full"] }