[package]
name = "twitch"
version = "0.1.0"
authors = ["jprochazk <honza.spacir@gmail.com>"]
edition = "2021"
license = "MIT"

[features]
simd = []

[dependencies]

[dev-dependencies]
irc-rust = "0.4.0"
twitch-irc = "5.0.0"

criterion = "0.5.1"
pretty_assertions = "1.0.0"

futures-util = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }
tokio-tungstenite = "0.19.0"

[[bench]]
name = "parse"
harness = false
path = "./benches/rust/parse.rs"

[profile.release]
lto = "fat"

[profile.release-debug]
inherits = "release"
debug = true
