[package]
name = "nanochat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch = { path = "../../", features = ["simd"] }
mimalloc = { version = "0.1.37", default-features = false }
futures-util = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }
tokio-tungstenite = "0.19.0"
uwuify = { version = "0.2.2", default-features = false }
beef = "0.5.2"
home = "0.5.5"

[profile.release]
lto = "fat"
