name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      - name: Tests (no default features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib --no-default-features

      - name: Tests (default features)
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Tests (all features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

